apiVersion: v1
kind: Service
metadata:
  name: m5-stub
  labels:
    app.kubernetes.io/name: m5-stub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: m5-stub
  ports:
    - name: http
      port: 8080
      targetPort: http
